Repository jenkins-x-plugins/jx-admin, pull requests merged in 2020-11, with the labels that each got.

#107 fix: lets preserve the wait behaviour if < 2 jobs
  pkg/cmd/joblog/joblog.go
Labels: approved, size/S

#110 fix: avoid switching http => https
  pkg/cmd/operator/operator.go
Labels: approved, size/XS

#113 fix: wait for pending pod to be ready
  pkg/cmd/joblog/joblog.go
Labels: approved, lgtm, ok-to-test, size/M

#119 fix: improve the UX around logs
  docs/cmd/jx-admin.md
  docs/cmd/jx-admin_create.md
  docs/cmd/jx-admin_invitation.md
  docs/cmd/jx-admin_log.md
  docs/cmd/jx-admin_operator.md
  docs/cmd/jx-admin_plugins.md
  docs/cmd/jx-admin_plugins_upgrade.md
  docs/cmd/jx-admin_trigger.md
  docs/cmd/jx-admin_upgrade.md
  docs/cmd/jx-admin_version.md
  docs/man/man1/jx-admin-log.1
  go.mod
  go.sum
  pkg/cmd/joblog/joblog.go
  pkg/cmd/operator/operator.go
Labels: approved, size/L

#121 fix: add an argument to add custom git setup commands
  pkg/cmd/operator/operator.go
Labels: approved, size/XS
