Repository jenkins-x-plugins/jx-admin, pull requests merged in 2020-10, with the labels that each got.

#78 chore: upgrade and align with kubernetes dependencies 0.19.2, also update to go 1.15
  .golangci.yml
  go.mod
  go.sum
  jenkins-x.yml
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/invitations/invitations.go
  pkg/cmd/joblog/joblog.go
  pkg/cmd/operator/operator.go
  pkg/cmd/plugins/plugins.go
  pkg/cmd/plugins/upgrade/upgrade.go
  pkg/cmd/root.go
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/upgrade/upgrade_test.go
  pkg/cmd/version/version.go
  pkg/envfactory/env_factory.go
  pkg/plugins/helmplugin/helm_plugin.go
  pkg/plugins/helpers.go
  pkg/reqhelpers/flags.go
  pkg/reqhelpers/helpers.go
  pkg/upgrader/helpers.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
Labels: approved, lgtm, size/L

#87 refactor: lets use jx-git-operator as the default operator namespace so it in consistent with Terraform
  pkg/common/constants.go
Labels: approved, size/XS

#99 fix: lets always log the URL to create a git token
  go.mod
  go.sum
  pkg/cmd/operator/operator.go
Labels: approved, size/S

#103 chore: upgrade helm
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/M
