Repository jenkins-x-plugins/jx-admin, pull requests merged in 2020-12, with the labels that each got.

#127 refactor: remove old v2 requirements
  go.mod
  go.sum
  jx/bdd/boot-lh-ghe/jx-requirements.yml
  jx/bdd/boot-vault/jx-requirements.yml
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/operator/operator.go
  pkg/cmd/root.go
  pkg/cmd/upgrade/test_data/helmfile/README.md
  pkg/cmd/upgrade/test_data/helmfile/env/dev.yaml
  pkg/cmd/upgrade/test_data/helmfile/env/production.yaml
  pkg/cmd/upgrade/test_data/helmfile/env/staging.yaml
  pkg/cmd/upgrade/test_data/helmfile/expected-jx-requirements.yml
  pkg/cmd/upgrade/test_data/jx-boot-gitops/README.md
  pkg/cmd/upgrade/test_data/jx-boot-gitops/env/dev.yaml
  pkg/cmd/upgrade/test_data/jx-boot-gitops/env/production.yaml
  pkg/cmd/upgrade/test_data/jx-boot-gitops/env/staging.yaml
  pkg/cmd/upgrade/test_data/jx-boot-gitops/expected-jx-requirements.yml
  pkg/cmd/upgrade/test_data/jx-install/README.md
  pkg/cmd/upgrade/test_data/jx-install/env/dev.yaml
  pkg/cmd/upgrade/test_data/jx-install/env/production.yaml
  pkg/cmd/upgrade/test_data/jx-install/env/staging.yaml
  pkg/cmd/upgrade/test_data/jx-install/expected-jx-requirements.yml
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/upgrade/upgrade_test.go
  pkg/envfactory/env_factory.go
  pkg/plugins/helpers.go
  pkg/reqhelpers/flags.go
  pkg/reqhelpers/helpers.go
  pkg/upgrader/helpers.go
  pkg/upgrader/upgrader.go
  pkg/upgrader/upgrader_test.go
Labels: approved, size/XXL

#130 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  go.sum
  pkg/cmd/create/create_test.go
  pkg/plugins/helpers.go
  pkg/reqhelpers/helpers.go
  pkg/upgrader/helpers.go
Labels: approved, size/M

#131 fix: add an arm image
  .goreleaser.yml
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  Dockerfile
  Dockerfile-preview
  build.sh
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, size/XL

#132 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot

#135 fix: upgrade pipeline
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#145 fix(doc): use correct link
  README.md
Labels: needs-ok-to-test, size/XS
