Repository jenkins-x-plugins/jx-admin, pull requests merged in 2021-01, with the labels that each got.

#161 fix: ugprade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/S

#162 chore: upgrade dependencies
  go.mod
  go.sum
Labels: approved, size/XS

#163 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#166 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#182 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#183 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#184 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#185 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#188 chore: upgrade deps
  go.mod
  go.sum
Labels: size/S

#167 chore: fix the broken link of jx 3
  README.md
Labels: needs-ok-to-test, size/XS

#190 fix: add a little retry waiting for the git operator deployment
  go.mod
  go.sum
  pkg/bootjobs/bootjobs.go
  pkg/cmd/joblog/joblog.go
Labels: approved, size/M

#191 fix: upgrade kube client
  go.mod
  go.sum
  pkg/cmd/joblog/joblog.go
  pkg/cmd/trigger/trigger.go
Labels: approved, size/M

#194 fix: add better validation for username
  go.mod
  go.sum
  pkg/bootjobs/bootjobs.go
  pkg/cmd/joblog/joblog.go
  pkg/cmd/operator/operator.go
  pkg/cmd/operator/operator_test.go
Labels: approved, size/L

#195 chore: upgrade jx admin
  go.mod
  go.sum
Labels: approved, size/XS

#197 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
