Repository jenkins-x-plugins/jx-admin, pull requests merged in 2022-05, with the labels that each got.

#244 fix: remove resource request from step template
  .lighthouse/jenkins-x/pullrequest.yaml
  go.mod
  go.sum
Labels: approved, size/M

#245 fix: update json iterator package to fix panic with logs
  go.mod
  go.sum
Labels: approved, size/S

#246 fix: created codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, ok-to-test, size/M
