Repository jenkins-x-plugins/jx-admin, pull requests merged in 2023-09, with the labels that each got.

#266 Updated go version to 1.19 in make file of jx-admin
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/upload-binaries.sh
  Makefile
  go.mod
Labels: approved, ok-to-test, size/M

#280 chore: upgrade release pipeline images
  .github/workflows/jenkins-x-release.yaml
Labels: size/S, updatebot

#281 fix: changelog
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/changelog.sh
Labels: size/XS, updatebot

#282 fix: typo in workflow
  .github/workflows/jenkins-x-release.yaml
Labels: size/XS, approved

#283 fix: switch to jx-boot for jx-changelog
  .github/workflows/jenkins-x-release.yaml
  Dockerfile
Labels: size/XS, approved

#278 feat: show logs in creation time order
  .github/workflows/jenkins-x-pr.yaml
  pkg/cmd/joblog/joblog.go
Labels: approved, size/M

#284 fix: add safe.directory
  .github/workflows/jenkins-x/changelog.sh
Labels: size/XS, approved

#285 fix: version
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/changelog.sh
  .github/workflows/plugins-pr.yaml
Labels: approved, size/S

#279 feat: add stop command
  pkg/cmd/joblog/joblog.go
  pkg/cmd/root.go
  pkg/cmd/stop/stop.go
Labels: approved, size/L
